### ISSUE TITLE
Change result of headers file

### ISSUE THREAD

**Issue by Omardavinci** [ArachisH/HabBit#1]
Hi again sorry for the mistake. My question is in the code, how i can change the result in headers file. For example it creates this:  // Outgoing[16, 074e3e3e82db7610dbeafd95c22d20a2] = ....// i want to change the result for example to this: The next header,16,074e3e3e82db7610dbeafd95c22d20a2. I did python program but i think in c# would be great.

**Comment by ArachisH** [comment]
Hi, can you change the format on this line of code: https://github.com/ArachisH/HabBit/blob/master/HabBit/Program.cs#L361

You would want to change it to something like this, for [Header, Hash]:
```cs
string dump = $"{messageType}[{messageHash}, {header}] = {messageName}{messageCtor}";
```
Instead of the default, [Hash, Header]:
```cs
string dump = $"{messageType}[{header}, {messageHash}] = {messageName}{messageCtor}";
```
