### ISSUE TITLE
Can I set the RSA public key and exponent with /rsa ?

### ISSUE THREAD

**Issue by jomp16** [ArachisH/HabBit#1]
In the old release of HabBit, I could add my _own_ RSA public key and exponent to Habbo.swf.

But seems now it just generates a new key every time when /rsa option is present (looking on HBOptions.cs).

This isn't good for me, because I need to replace the keys every time on my server when I update Habbo.swf.

I could recompile HabBit again with my keys on HBRSAKeys, but I wont do this.

I ask you to add something like a `if (args.size >= 2) get public key and exponent` somewhere in this file: https://github.com/ArachisH/HabBit/blob/master/HabBit/Utilities/HBOptions.cs#L135.

Thank you!

**Comment by jomp16** [comment]
Will this work? https://github.com/jomp16/HabBit/commit/d773198a32de1d9d6868cabfaf6b74306362c4b7

Sorry for code formatting, I don't know how to configure Monodevelop.

Imma test here.

**Comment by jomp16** [comment]
I found why: var Keys on Program.cs is null, I replaced with Options.Keys and it worked perfectly.

**Comment by jomp16** [comment]
Fix commit: https://github.com/jomp16/HabBit/commit/53b4974f2944a65f7e711518726491962f742ee7

**Comment by jomp16** [comment]
Check out pull request: https://github.com/ArachisH/HabBit/pull/2

**Comment by ArachisH** [comment]
Thanks for that my man, and I'll try not to delete my GitHub again.
