### ISSUE TITLE
Feature request: add debbuging to Habbo.swf

### ISSUE THREAD

**Issue by jomp16** [ArachisH/HabBit#2]
I could work on it and do a pull request, but I don't know how your FlashInspect works. So I'll submit an issue with a lots of details to you add.

---

_This example uses the Habbo.swf from "**PRODUCTION-201612121204-107735592**"_

I found that the Habbo.swf contains a lot of calls to a class with static method log like `_-3Jx.log("some string")`

The class and methods from AS3 Sorcerer is the following:

```
//------------------------------------------------------------
//_SafeStr_4

package {
    import _-5D9._SafeStr_7;

    public class _SafeStr_4 {

        public static var listener:_SafeStr_7;


        public static function log(... k):void{
        }


    }
}//package 

// _SafeStr_4 = "_-3Jx" (String#2365, DoABC#2)
// _SafeStr_7 = "_-6kp" (String#3092, DoABC#2)
```

As you can see, the method log() is empty.

What I did? I decompiled with RABCDAsm, searched for _-3Jx.class.asasm, here's the log() method:

```
 trait method QName(PackageNamespace("", "#0"), "log") flag FINAL dispid 3
  method
   refid "_-3Jx/class/log"
   returns QName(PackageNamespace("", "#0"), "void")
   flag NEED_REST
   body
    maxstack 1
    localcount 2
    initscopedepth 3
    maxscopedepth 4
    code
     debugfile           "k"
     debugline           16
     getlocal0
     pushscope

     debug               1, "k", 0, 16
     debugline           28
     returnvoid
    end ; code
   end ; body
  end ; method
 end ; trait
```
And since I don't know how to create the bytecodes for looping the varargs k, and the entire Habbo.swf only uses log() with one string, I found safe to remove the varargs and set the var to String.

So I added the following line: `   param QName(PackageNamespace(""), "String")`

before `returns QName(PackageNamespace("", "#0"), "void")` and removed the `   flag NEED_REST`
to remove the varargs.

I wanted to log everything to FlashExternalInterface I had on my client. so I found there's a class called Core with static method debug() in package `_-55D`

```
public static function debug(k:String):void{
    if (_SafeStr_18763){
        _SafeStr_18763.debug(k);
    };
    if (ExternalInterface.available){
        ExternalInterface.call("FlashExternalInterface.logDebug", k);
    };
}
```

I added the following lines before returnvoid:

```
     getlex              QName(PackageNamespace("_-55D"), "Core")
     getlocal1
     callpropvoid        QName(PackageNamespace("", "#0"), "debug"), 1
```

For some reason, if I don't change `maxstack 1` to `maxstack 2`. The client does nothing. So I changed that.

Final code:

```
 trait method QName(PackageNamespace("", "#0"), "log") flag FINAL dispid 3
  method
   refid "_-3Jx/class/log"
   param QName(PackageNamespace(""), "String")
   returns QName(PackageNamespace("", "#0"), "void")
   body
    maxstack 2
    localcount 2
    initscopedepth 3
    maxscopedepth 4
    code
     debugfile           "k"
     debugline           16
     getlocal0
     pushscope

     debug               1, "k", 0, 16
     debugline           28

     getlex              QName(PackageNamespace("_-55D"), "Core")
     getlocal1
     callpropvoid        QName(PackageNamespace("", "#0"), "debug"), 1

     returnvoid
    end ; code
   end ; body
  end ; method
 end ; trait
```

New log() decompiled with AS3 Sorcerer:

```
public static function log(k:String):void
{
    Core.debug(k);
}
```
Screen of the console from Chrome: [http://i.imgur.com/gmr3aRd.png](http://i.imgur.com/gmr3aRd.png)
[client_interface.js](https://gist.github.com/jomp16/36bb0e2caf2390861258bef2905e8e59)

**Comment by sant0ro** [comment]
Woah! That's just amazing.

**Voted Up** this feature request.

So you're thinking that HabBit can have a feature (argument) called --with-debug (as an example)
That in the crack process also adds those changes allowing to debug all triggers in the SWF?

(Since this is good for Development, but i don't recommend for Production)... That can help a lot.

**Comment by jomp16** [comment]
Yeah, exactly!

Since I'm on Linux, no Flash Player Debugger (and seems they removed everything like `trace()`, or debug and debugline is trace()?)

**Comment by sant0ro** [comment]
@jomp16 yes, in the new Habbo JavaScript API (from the beta.habbo.com - actually habbo.com) they removed all those stuff. When SWF crashes the Error Dump was quite useful. Now or isn't given or is Url Encoded with less details.

**Comment by jomp16** [comment]
Oops, `StringUtils.trim()` added by mistake on the final code.

I haven't managed to trim the string, I'm pretty sure I added the bytecode correctly, but the Habbo.swf screen is just black (no dc or something like this). Maybe something related to maxstack? I changed to 4, nothing, 5, still nothing,so  I gave up. It's working fine, even with some lines contains empty spaces on start and end.

Maybe I'll add trim() to client_interface.js

**Comment by Speaqer** [comment]
Arachis told my friend that he broke something in FlashInspect and is recoding it now. It might mean that this will need to wait until that. Btw, This is very gr8 idea!

**Comment by ArachisH** [comment]
I've actually had this on HabBit at some point, but since I never had any use for the logs I didn't think anyone else would find them useful either. I really appreciate how much detail this request/issue has, I'll look into adding this feature to the current branch/build that's on here(mines broken).

Just so we're clear, you just want to re-enable the log method, so it ends up looking like this:
```
public static function log(k:String):void
{
    Core.debug(k);
}
```

**Comment by jomp16** [comment]
Yes! I think this is useful for some of us :)

(And I don't wanna to decompile and modify it every new release :P)

Em qua, 14 de dez de 2016 5:28 PM, The Old Nut Man <notifications@github.com>
escreveu:

**Comment by ArachisH** [comment]
As for the max stack problem you encountered, this was because max stack tells the VM the maximum amount of values that will be pushed onto the operand stack. Since you added a **getlex**, and a **callpropvoid** instruction to the instruction list, it needed to push(getlex) the multiname, and then push "local1" to the stack, making the new max 2.

getlex - push "Core"
getlocal1 - push from register[1]

**Comment by jomp16** [comment]
TIL that maxstack is very useful.

Question: can't I change maxstack to an high number, like 2147483647 and don't worry about things?

And can you explain why StringUtil.trim() didn't work on client (just black screen)? I guess that's because of the stack. Correct?

Unfortunately I don't have the code I tried here anymore, but AS3 Sorcerer did show `Core.debug(StringUtils.trim(k))`

**Comment by ArachisH** [comment]
I don't think anything bad will happen if you set a high value for max stack when you know you won't be using all of it, I know for a fact though that it'll break if max stack isn't high enough.

StringUtils most likely broke due to the invalid(too low) of a max stack value, since it would require a value of 3 with getlex "StringUtils".

I can add that in though, no problem.

**Comment by jomp16** [comment]
"I can add that in though, no problem."

No need, for some whatever the reason is, maxstack 3 and the above piece of bytecode just gives me a black client, and since I don't have flash debugger here, I can't see if Habbo.swf threw any exceptions.

Just do Core.debug(k), that works (tm)

**Comment by ArachisH** [comment]
Yea sure man, as long as you know the procedure to it.

**Comment by ArachisH** [comment]
Sorry I took a while, it's done though. I will push the update in a bit, but first I need to make sure of some stuff.
[](http://i.imgur.com/2sjbooU.png)

**Comment by jomp16** [comment]
Yep. It's working. Thanks!

byw; you should update the README.md
