### ISSUE TITLE
Param /log does nothing

### ISSUE THREAD

**Issue by jomp16** [ArachisH/HabBit#3]
Version: HabBit v4.0.9

Command line: `HabBit.exe "PRODUCTION-201702071205-725807044\Habbo_ORIGINAL.swf" /dhost /dump /log /rsa "xxx" "xxx"`

See:

```
//------------------------------------------------------------
//_SafeStr_4

package 
{
    import _-5wd._SafeStr_7;

    public class _SafeStr_4 
    {

        public static var listener:_SafeStr_7;


        public static function log(... k):void
        {
        }


    }
}//package 
```

Excepted behavior is HabBit to replace with Core.debug(local1), like you did in a old version.

```
//------------------------------------------------------------
//_SafeStr_4

package 
{
    import _-5wd._SafeStr_7;
    import _-4Gp.Core;

    public class _SafeStr_4 
    {

        public static var listener:_SafeStr_7;


        public static function log(k:String):void
        {
            Core.debug(k);
        }


    }
}//package 
```

**Comment by jomp16** [comment]
Because a lot of code still uses _SafeStr_4 like this:

```_SafeStr_4.log(((("Received console msg: " + _local_2._SafeStr_7090) + ", ") + _local_2.senderId));```

**Comment by ArachisH** [comment]
Oh yea, I changed the functionality of the /log command. Right now it just dumps the outgoing message values to the web console, I'll revert it back to doing this though, since the message logging seems pretty useless(with Tanji out there and all).

**Comment by jomp16** [comment]
May I suggest you to rename that to other param name? Since I use Linux, no
Tanji for me.

Actually I never saw that, later I'll see on home.

Thanks

Em 9 de fev de 2017 6:47 PM, "The Old Nut Man" <notifications@github.com>
escreveu:

**Comment by ArachisH** [comment]
Alright, there will be two arguments then:
* /mlog - Logging Outgoing/(Incoming later) messages to console.
* /dlog - Enabling the internal global debug method.

**Comment by ArachisH** [comment]
Feature has been introduced: https://github.com/ArachisH/HabBit/releases/tag/v4.0.105.0
