### ISSUE TITLE
Improve Message files regex

### ISSUE THREAD

**Issue by jomp16** [ArachisH/HabBit#4]
For some reason, your Matcher isn't working on my header classes:

My Incoming and Outgoing classs: https://gist.github.com/jomp16/d88b65b08d2b405a1069756aae39f8b8
The HabBit result: https://gist.github.com/jomp16/65f1ad684ec386158cef79f5d8bf1efd

I think we should rework more on Regex, don't ya think so?

In meantime I'm still using the first version of HabBit header update (modified by me to support Linux and \n and \r\n), which works as excepted and perfectly fine: https://gist.github.com/jomp16/2d0882e037284708a12c19558368c530

Seems my regex on HabBit first version is: `(\b(?<header>\d{1,4})\b)(?<end>[^\r|^\n|$]*)`

**Comment by jomp16** [comment]
Maybe trim all comments with regex, and then matching **only** the numbers, not some text alongside the numbers?

**Comment by jomp16** [comment]
Regex `(?<start>(.*?))\b(?<header>\d{1,4})\b(?<end>[^\r|^\n|$]*)` gives: https://gist.github.com/jomp16/705016e24804e6a0affd7c520bbc0e7b

Almost good, maybe trim all comments?

And yeah: `//! Duplicate Matches(3263)` -- It was easy to fix on first version of HabBit: 

```
if (curSimilars.Count == 1) {
    ushort curHeader = current.GetMessageHeader(curMsgClass);
    result = $"{curHeader}{endValue} // {headerValue}";
} else {
    notFound = true;

    foreach (ASClass curMsgClass1 in curSimilars) {
        if (notFound && curMsgClass.Instance.QualifiedName.Name == curMsgClass1.Instance.QualifiedName.Name) {
            result = $"{current.GetMessageHeader(curMsgClass1)}{endValue} // {headerValue}";

            notFound = false;
        }
    }

    if (notFound) {
        result = $"-1{endValue} // Hella lot matches: Original: {msgClass.Instance.QualifiedName.Name}[{headerValue}] | {hash}";
    }
}
```

Explanation: since some messages has exactly the same class name, I checked for any classes which matches the class name of header ID.

Maybe you can add this feature?

**Comment by ArachisH** [comment]
https://gist.github.com/ArachisH/f9d76b8f8a61f8208c4c9d7c8b972e3b
Just pushed a [commit](01bba26de355cb4a38dbde221a47ee4c30e74c4d) that applies the fixes found in the gist, and also the attempt to match by name if duplicates are present.

**Comment by jomp16** [comment]
Cool! Almost there!

I think this should be a new issue: why `const val USER_RIGHTS = -1 //! Zero Matches(3604)` and `const val MODERATION_ROOM_INFO = -1 //! Duplicate Matches(1894)` isn't being matched by HabBit? Old version correctly matches as excepted.

Maybe your message hash generator is too accurate?

**Comment by ArachisH** [comment]
Yea, it's a bit more different to work with older client builds. I'll see what I can do later this week, maybe I can improve it a bit more.
